# Eksplorasi Dataset Korpus, QA, dan Evaluasi
Notebook ini digunakan untuk memperlihatkan sampel data dari korpus dan QA, dengan kolom panjang di-truncate, serta menampilkan hasil evaluasi dari file `evaluation_results.pkl`.

## 1. Import Libraries dan Load Dataset

In [1]:
import pandas as pd
from pathlib import Path

corpus_path = Path('data/corpus.parquet')
qa_path = Path('data/qa.parquet')

if corpus_path.exists():
    df_corpus = pd.read_parquet(corpus_path)
    print('Korpus loaded:', df_corpus.shape)
else:
    df_corpus = None
    print('Korpus file not found')

if qa_path.exists():
    df_qa = pd.read_parquet(qa_path)
    print('QA loaded:', df_qa.shape)
else:
    df_qa = None
    print('QA file not found')

Korpus loaded: (2469, 3)
QA loaded: (600, 4)

## 2. Tampilkan Sampel Data Korpus

In [2]:
if df_corpus is not None:
    sample_corpus = df_corpus.head(5).copy()
    if 'contents' in sample_corpus.columns:
        sample_corpus['contents'] = sample_corpus['contents'].astype(str).str.slice(0, 100) + '...'
    display(sample_corpus)
else:
    print('Korpus belum dimuat.')

,doc_id,contents,metadata
0,dc9b290175ed088f3ca2693e3dbe6657,Cultivation and propagation of Alfalfa (Part 1...,"{'category': None, 'chunk': 0, 'disease': None..."
1,86e3f1bdfc14b608cf542abfc4c71dd6,Cultivation and propagation of Alfalfa (Part 2...,"{'category': None, 'chunk': 1, 'disease': None..."
2,4ac60b94f1274d11049d9c1890f68841,Cultivation and propagation of Alfalfa (Part 3...,"{'category': None, 'chunk': 2, 'disease': None..."
3,000c02afaa99c383e009d5b8bec410c6,Disease: Alfalfa Mosaic affecting Alfalfa\n\nS...,"{'category': 'viral', 'chunk': 0, 'disease': '..."
4,371dc94f4a33c620005ea78fc9a44c0b,Disease: Anthracnose affecting Alfalfa\n\nSymp...,"{'category': 'fungal', 'chunk': 0, 'disease': ..."

## 3. Tampilkan Sampel Data QA

In [3]:
if df_qa is not None:
    sample_qa = df_qa.head(5).copy()
    if 'generation_gt' in sample_qa.columns:
        sample_qa['generation_gt'] = sample_qa['generation_gt'].astype(str).str.slice(0, 100) + '...'
    display(sample_qa)
else:
    print('QA belum dimuat.')

,qid,query,retrieval_gt,generation_gt
0,da25227f-1b4e-4907-81e2-a3b3fef62300,What are the basic requirements for Alfalfa to...,[[dc9b290175ed088f3ca2693e3dbe6657]],"['Alfalfa grows best in deep, fertile, well-dr..."
1,bb8ccee4-864e-44f4-9ea6-598836b4a546,What guideline dictates that you can plant alf...,[[86e3f1bdfc14b608cf542abfc4c71dd6]],"[""The guideline dictates that you can plant al..."
2,ef6bcdcb-ccd6-430b-9471-8c00c3debf41,What are the various considerations for harves...,[[4ac60b94f1274d11049d9c1890f68841]],['Alfalfa is harvested at different times depe...
3,d7ff8aae-2f36-4f9a-a1e2-a26ec4fd686b,What describes Alfalfa Mosaic affecting Alfalf...,[[000c02afaa99c383e009d5b8bec410c6]],['Alfalfa Mosaic affecting Alfalfa is characte...
4,44332568-7c88-40ee-9dbb-1eb78d42f932,"What defines Anthracnose affecting Alfalfa, co...",[[371dc94f4a33c620005ea78fc9a44c0b]],['Anthracnose affecting Alfalfa is defined by ...

## 4. Truncate Kolom Panjang pada Sampel

In [4]:
def truncate_string(s, length=100):
    if pd.isnull(s):
        return s
    s = str(s)
    return s[:length] + ('...' if len(s) > length else '')

# Contoh penggunaan pada korpus
df_corpus_trunc = None
df_qa_trunc = None
if df_corpus is not None:
    df_corpus_trunc = df_corpus.copy()
    if 'contents' in df_corpus_trunc.columns:
        df_corpus_trunc['contents'] = df_corpus_trunc['contents'].apply(lambda x: truncate_string(x, 100))
    display(df_corpus_trunc.head(3))

# Contoh penggunaan pada QA
if df_qa is not None:
    df_qa_trunc = df_qa.copy()
    if 'generation_gt' in df_qa_trunc.columns:
        df_qa_trunc['generation_gt'] = df_qa_trunc['generation_gt'].apply(lambda x: truncate_string(x, 100))
    display(df_qa_trunc.head(3))

,doc_id,contents,metadata
0,dc9b290175ed088f3ca2693e3dbe6657,Cultivation and propagation of Alfalfa (Part 1...,"{'category': None, 'chunk': 0, 'disease': None..."
1,86e3f1bdfc14b608cf542abfc4c71dd6,Cultivation and propagation of Alfalfa (Part 2...,"{'category': None, 'chunk': 1, 'disease': None..."
2,4ac60b94f1274d11049d9c1890f68841,Cultivation and propagation of Alfalfa (Part 3...,"{'category': None, 'chunk': 2, 'disease': None..."

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## 5. Load dan Tampilkan Hasil Evaluasi

In [ ]:
import os
import pickle

pkl_path = 'evaluation_results.pkl'
if os.path.exists(pkl_path):
    eval_results = pd.read_pickle(pkl_path)
    if isinstance(eval_results, pd.DataFrame):
        display(eval_results.head(5))
    else:
        print(type(eval_results))
        print(str(eval_results)[:500])
else:
    print('File evaluation_results.pkl tidak ditemukan.')